### ISSUE TITLE
Enabling syncing causes CTD

### ISSUE THREAD

**Issue by nosixx** [tarzasai/Uoccin#3]
When I check the synchronization checkbox in the settings menu the app closes to the home screen without any error messages.  Please look into this.

**Comment by tarzasai** [comment]
uhm, did you choose the google account before? can you tell me your phone brand and model?

**Comment by nosixx** [comment]
Yes, my Gmail account was selected beforehand. My phone is a LG G2 Running Android version 4.4.2

**Comment by tarzasai** [comment]
should be very similar to my nexus 5... is it android stock, or a custom rom?

**Comment by nosixx** [comment]
It is a stock rom,  but I did root it, but I don't think that would matter.

**Comment by tarzasai** [comment]
I'm sorry but it doesn't happen in any circumstances on my phones. btw, when you relaunch the app and go in the settings, is the synchronization still disabled?

**Comment by nosixx** [comment]
No. After a restart the checkbox is checked off so I am assuming that means
it will sync from that point forward, but I have not verified that yet.

**Comment by tarzasai** [comment]
well, there's a "synchronize now" option in the left side menu, let me know if it works.

**Comment by RoundSparrow** [comment]
Mine crashes when I  try to Sync (Google Drive) on Android 5.1.1, Nexus 5, Stock factory ROM.  I submitted a crash report you should see in Google Play on your side.

**Comment by tarzasai** [comment]
thank you. I just published a fix, you should get an update in few hours.

**Comment by RoundSparrow** [comment]
Version 1.5 updated from Google Play: Crash is gone now, and it did create folders on my Google Drive.  Thank you.

**Comment by tarzasai** [comment]
glad to hear that.
